// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/attack_detection.proto

package attackdetectionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttackDetection_Predict_FullMethodName = "/AttackDetection/Predict"
)

// AttackDetectionClient is the client API for AttackDetection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttackDetectionClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
}

type attackDetectionClient struct {
	cc grpc.ClientConnInterface
}

func NewAttackDetectionClient(cc grpc.ClientConnInterface) AttackDetectionClient {
	return &attackDetectionClient{cc}
}

func (c *attackDetectionClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, AttackDetection_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttackDetectionServer is the server API for AttackDetection service.
// All implementations must embed UnimplementedAttackDetectionServer
// for forward compatibility.
type AttackDetectionServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	mustEmbedUnimplementedAttackDetectionServer()
}

// UnimplementedAttackDetectionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttackDetectionServer struct{}

func (UnimplementedAttackDetectionServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedAttackDetectionServer) mustEmbedUnimplementedAttackDetectionServer() {}
func (UnimplementedAttackDetectionServer) testEmbeddedByValue()                         {}

// UnsafeAttackDetectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttackDetectionServer will
// result in compilation errors.
type UnsafeAttackDetectionServer interface {
	mustEmbedUnimplementedAttackDetectionServer()
}

func RegisterAttackDetectionServer(s grpc.ServiceRegistrar, srv AttackDetectionServer) {
	// If the following call panics, it indicates UnimplementedAttackDetectionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttackDetection_ServiceDesc, srv)
}

func _AttackDetection_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttackDetectionServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttackDetection_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttackDetectionServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttackDetection_ServiceDesc is the grpc.ServiceDesc for AttackDetection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttackDetection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AttackDetection",
	HandlerType: (*AttackDetectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _AttackDetection_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/attack_detection.proto",
}
