// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/attack_detection.proto

package attackdetectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_attack_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attack_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_attack_detection_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PredictRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PredictRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PredictRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PredictRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PredictRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PredictRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    string                 `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_attack_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attack_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_attack_detection_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

var File_proto_attack_detection_proto protoreflect.FileDescriptor

const file_proto_attack_detection_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/attack_detection.proto\"\x88\x02\n" +
	"\x0ePredictRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x126\n" +
	"\aheaders\x18\x06 \x03(\v2\x1c.PredictRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\tR\n" +
	"prediction2?\n" +
	"\x0fAttackDetection\x12,\n" +
	"\aPredict\x12\x0f.PredictRequest\x1a\x10.PredictResponseB9Z7request-extractor/gen/attackdetection;attackdetectionpbb\x06proto3"

var (
	file_proto_attack_detection_proto_rawDescOnce sync.Once
	file_proto_attack_detection_proto_rawDescData []byte
)

func file_proto_attack_detection_proto_rawDescGZIP() []byte {
	file_proto_attack_detection_proto_rawDescOnce.Do(func() {
		file_proto_attack_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_attack_detection_proto_rawDesc), len(file_proto_attack_detection_proto_rawDesc)))
	})
	return file_proto_attack_detection_proto_rawDescData
}

var file_proto_attack_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_attack_detection_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: PredictRequest
	(*PredictResponse)(nil), // 1: PredictResponse
	nil,                     // 2: PredictRequest.HeadersEntry
}
var file_proto_attack_detection_proto_depIdxs = []int32{
	2, // 0: PredictRequest.headers:type_name -> PredictRequest.HeadersEntry
	0, // 1: AttackDetection.Predict:input_type -> PredictRequest
	1, // 2: AttackDetection.Predict:output_type -> PredictResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_attack_detection_proto_init() }
func file_proto_attack_detection_proto_init() {
	if File_proto_attack_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_attack_detection_proto_rawDesc), len(file_proto_attack_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_attack_detection_proto_goTypes,
		DependencyIndexes: file_proto_attack_detection_proto_depIdxs,
		MessageInfos:      file_proto_attack_detection_proto_msgTypes,
	}.Build()
	File_proto_attack_detection_proto = out.File
	file_proto_attack_detection_proto_goTypes = nil
	file_proto_attack_detection_proto_depIdxs = nil
}
